# This is an example setting for MCMC fitting of Mocos Sim
#data = "true_trajectory2.jld2" # or provide --data arg to cli.jl
#population = "poland_v3.jld2"  # or provide -- population arg to cli.jl

param_seed = 0
move_seed = 0

num_samples = 100
max_daily_detections = 25000
max_total_detections = 1000000

num_initial = 100

[initials]
c = 1.35
b = 0.1
q = 0.1
mloc = 2000
msca = 100
mlim = 1.0

[moves]
c = 0.03
b = 0.03
q = 0.03
# the not given parameters are frozen

