# This is example setting for MCMC fitting of Mocos Sim


#population = "poland_v3.jld2"
param_seed = 0

move_seed = 1234678

#data = "true_trajectory2.jld2"

num_samples = 100
max_daily_detections = 25000
max_total_detections = 1000000

num_initial = 100
